version: '3.4'
services:
  # Userse service
  users:
    container_name: users
    build:
      context: ./services/users
      dockerfile: Dockerfile-prod
    volumes:
      - './services/users:/usr/src/app'
    # ports:
    #   - 5001:5000
    expose:
      - '5000'
    environment:
      - FLASK_DEBUG=0
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgresql://postgres:postgres@users-db:5432/users_prod
      - DATABASE_TEST_URL=postgresql://postgres:postgres@users-db:5432/users_test
    depends_on:
      - users-db
    links:
      - users-db
  # DB service
  users-db:
    container_name: users-db
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  # Nginx service
  nginx:
    container_name: nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - client
  # client service
  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile-prod
    args:
      - NODE_ENV=production
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    ports:
      - '3007:80'
    depends_on:
      - users
    links:
      - users
